version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - veefriends-network
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/veefriends-game
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - veefriends-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=veefriends-game
      # Uncomment and set these if you want authentication
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=secure-password

networks:
  veefriends-network:
    driver: bridge

volumes:
  mongodb_data:
